server:
  port: 8087

spring:
  application:
    name: identity-service
  datasource:
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5440/identity
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        service-name: identity-service
        instance-id: ${spring.application.name}:${server.port}
  rabbitmq:
    addresses: localhost:5672

app:
  config:
    verification-email-subject : ${VERIFICATION_EMAIL_SUBJECT}
    forget-password-email-subject : ${FORGET_PASSWORD_EMAIL_SUBJECT}
  rabbitmq:
    internal-exchange : internal.exchange
    email-routing-key : internal.email.routing-key
  base-url : ${BASE_URL}
  security:
    confirmation-token:
      expires-in: 900 # value provided in seconds 15 minutes

    jwt:
      issuer : ${ISSUER}
      secret : ${JWT_SECRET}
      expires-in : 900 # The value is provided in seconds  // 15 minutes
      refresh-token:
        expires-in : 604800 # The value is provided in seconds 7 days
